export default {
  ALBUMS_REQUEST: '@@albums/ALBUMS_REQUEST',
  ALBUMS_SUCCESS: '@@albums/ALBUMS_SUCCESS',
  ALBUMS_FAILURE: '@@albums/ALBUMS_FAILURE',

  PHOTOS_REQUEST: '@@albums/PHOTOS_REQUEST',
  PHOTOS_SUCCESS: '@@albums/PHOTOS_SUCCESS',
  PHOTOS_FAILURE: '@@albums/PHOTOS_FAILURE',
};
